
# theme = "gruvbox_dark_hard"
theme = "hardcore"
# theme = flexoki_dark
# theme = gruber-darker
# theme = heisenberg
# theme = molokai
# theme = monokai_soda
# theme = papercolor-dark
# theme = "catppuccin_mocha"
# theme = "onedark"

[keys.select]
"Y" = "goto_line_end"

# Create a new minor mode
[keys.normal."+"]
m = ":run-shell-command cargo run"
h = ":run-shell-command cabal run"

[editor]
line-number = "relative"
scrolloff = 20
auto-save = true
auto-completion = true
shell = ["bash", "-c"]
bufferline = "multiple"
end-of-line-diagnostics = "hint"
#completion-replace = true

rulers = [80, 100]


#indent-style = 't'

[editor.inline-diagnostics]
cursor-line = "error"
other-lines = "error"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.file-picker]
max-depth = 10
ignore = true # reads from .ignore
hidden = true # ignore hidden files?
git-ignore = true

[editor.indent-guides]
render = true
character = "┆" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 0

[editor.soft-wrap]
enable = true # Should soft wrapping be enabled?
#wrap-at-text-width = true # Wrap at max fixed length instead of using all space.

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

