[[language]]
name = "dockerfile"
scope = "text.docker"
file-types = ["docker", "podman", "image", "Containerfile", "Dockerfile"]
roots = []

[[language]]
name = "cabal"
scope = "text.cabal"
file-types = ["cabal"]
roots = []

[[language]]
name = "python"
auto-format = true
roots = []
formatter = { command = "ruff", args = ["format", "-"] }
# Ruff works but doesn't support go-to definition
# You can pair it with another language server which does.
# It does however provide in-line, diagnostics which are nice.
language-servers = ["pylsp", "ruff"]

[[language]]
name = "yaml"
scope = "source.yaml"
file-types = ["sls", "yml", "yaml"]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
language-servers = [ "yaml-language-server", "ansible-language-server" ]
injection-regex = "yml|yaml"

[[language]]
name = "groovy"
language-id = "groovy"
scope = "source.groovy"
# file-types = ["groovy", "jenkinsfile", { glob = "Jenkinsfile" },  { glob = "Jenkinsfile.*" }]
file-types = ["groovy", "jenkinsfile", "Jenkinsfile"]
shebangs = ["groovy"]
comment-token = "//"
indent = { tab-width = 2, unit = "  " }
roots = []

[[grammar]]
name = "groovy"
source = { git = "https://github.com/Decodetalkers/tree-sitter-groovy", rev = "7e023227f46fee428b16a0288eeb0f65ee2523ec" }
