let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()
    Plug 'morhetz/gruvbox'
    Plug 'vim-scripts/AutoComplPop'
    Plug 'junegunn/fzf', {'do': { -> fzf#install()}}
    Plug 'junegunn/fzf.vim'
    Plug 'junegunn/goyo.vim' " Zenmode but for vim
    Plug 'makerj/vim-pdf'
call plug#end()

syntax on


" ============Configuration==============

set background=dark
colorscheme gruvbox
highlight NORMAL ctermbg=NONE

noh
"nnoremap <silent> <leader>n :nohlsearch<CR>
set noerrorbells
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set smartcase
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set incsearch
set nu
set number relativenumber
set nu rnu
set scrolloff=10
set shortmess-=F
set foldmethod=indent
set clipboard=unnamedplus 
set completeopt=menuone,longest,preview
set complete+=kspell
set shortmess+=c
set wildmenu

" wrap
set breakindent
set lbr
set formatoptions=l

