let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()
    Plug 'morhetz/gruvbox'

call plug#end()

syntax on

set background=dark
colorscheme gruvbox
highlight NORMAL ctermbg=NONE

noh
"nnoremap <silent> <leader>n :nohlsearch<CR>
set noerrorbells
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set nowrap
set smartcase
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set incsearch
set nu
set number relativenumber
set nu rnu
set scrolloff=10
set shortmess-=F
set foldmethod=indent


